# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Temp/xsvece00/PLD/CV11/SOURCES/BD/zync_blockdesign/ip/zync_blockdesign_processing_system7_0_0/zync_blockdesign_processing_system7_0_0.xci
# IP: The module: 'zync_blockdesign_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Temp/xsvece00/PLD/CV11/SOURCES/BD/zync_blockdesign/ip/zync_blockdesign_processing_system7_0_0/zync_blockdesign_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_blockdesign_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Temp/xsvece00/PLD/CV11/SOURCES/BD/zync_blockdesign/ip/zync_blockdesign_processing_system7_0_0/zync_blockdesign_processing_system7_0_0.xci
# IP: The module: 'zync_blockdesign_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Temp/xsvece00/PLD/CV11/SOURCES/BD/zync_blockdesign/ip/zync_blockdesign_processing_system7_0_0/zync_blockdesign_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_blockdesign_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
