# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Temp/xsvece00/PLD/CV11/SOURCES/rp_top.xdc

# Block Designs: C:/Temp/xsvece00/PLD/CV11/SOURCES/BD/zync_blockdesign/zync_blockdesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_blockdesign || ORIG_REF_NAME==zync_blockdesign} -quiet] -quiet

# IP: c:/Temp/xsvece00/PLD/CV11/SOURCES/BD/zync_blockdesign/ip/zync_blockdesign_processing_system7_0_0/zync_blockdesign_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_blockdesign_processing_system7_0_0 || ORIG_REF_NAME==zync_blockdesign_processing_system7_0_0} -quiet] -quiet

# IP: c:/Temp/xsvece00/PLD/CV11/SOURCES/BD/zync_blockdesign/ip/zync_blockdesign_axi_gpio_0_0/zync_blockdesign_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_blockdesign_axi_gpio_0_0 || ORIG_REF_NAME==zync_blockdesign_axi_gpio_0_0} -quiet] -quiet

# IP: c:/Temp/xsvece00/PLD/CV11/SOURCES/BD/zync_blockdesign/ip/zync_blockdesign_ps7_0_axi_periph_0/zync_blockdesign_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_blockdesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==zync_blockdesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: c:/Temp/xsvece00/PLD/CV11/SOURCES/BD/zync_blockdesign/ip/zync_blockdesign_rst_ps7_0_125M_0/zync_blockdesign_rst_ps7_0_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_blockdesign_rst_ps7_0_125M_0 || ORIG_REF_NAME==zync_blockdesign_rst_ps7_0_125M_0} -quiet] -quiet

# IP: c:/Temp/xsvece00/PLD/CV11/SOURCES/BD/zync_blockdesign/ip/zync_blockdesign_auto_pc_0/zync_blockdesign_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_blockdesign_auto_pc_0 || ORIG_REF_NAME==zync_blockdesign_auto_pc_0} -quiet] -quiet

# XDC: C:/Temp/xsvece00/PLD/CV11/SOURCES/BD/zync_blockdesign/zync_blockdesign_ooc.xdc
